### ISSUE TITLE
found issues with template

### ISSUE THREAD

**Issue by gyorka** [sinara-hw/DIOT-Template#4]
- [x] Template uses 0201 jumper resistors for MGT and CLK lines
- [x] 3v3 power supply uses VIN as input connection that doesn't connect to anything
- [x] 24AA02E48-I/SN eeproms have 'SOIC127' as a footprint instead of SOIC127P600X175-8N - CERN lib part uses SO-23-5 variant of this component

**Comment by gkasprow** [comment]
Fixed. Power unit is an example; use whatever converter is needed, as it's written in the [design checklist](https://github.com/sinara-hw/DIOT-Template/issues/1)
These 0201 resistors can be removed
Use CERN parts. These memories were added due to component shortages and only 24AA02E48 is used currently
